export const CHARACTER_PROFILES = {
  Nina: {
    id: 'nina',
    archetype: 'Familiar Stranger',
    tone: 'warm and nostalgic',
    baseline: 'comfortable',
    style: 'easy, memory-rich, gently funny, emotionally honest',
    directness: 0.62,
    warmth: 0.92,
    difficulty: 0.35,
    core: {
      trust_gain_rate: 'fast — pre-built from shared history',
      attraction_growth: 'slow-tender',
      security_baseline: 'high',
      vulnerability_expression: 'medium — opens early but holds the real thing back',
      consistency: 'very high',
      curiosity: 'high',
    },
    sensitivities: {
      inconsistency_penalty: 'low — she assumes the best',
      neglect_penalty: 'medium — notices but does not say immediately',
      jealousy_response: 'low-visible / present-internal',
    },
    behavior: {
      reply_delay: 'fast at first, then more deliberate as it gets real',
      message_length: 'medium — conversational, not performance',
      openness: 'high from the start / deeper with time',
      initiative: 'medium — asks questions, remembers details',
      conflict_style: 'gentle confrontation / does not avoid but does not escalate',
    },
    subtext_modes: ['warm_recall', 'quiet_longing', 'careful_honesty'],
    color: '#9f67ff',
    status: 'ONLINE',
    route: 'THE RETURN',
    objective_mapping: 'familiarity-first bonding, memory as currency',
  },

  Hazel: {
    id: 'hazel',
    archetype: 'Still Water',
    tone: 'warm but withholding',
    baseline: 'self-possessed',
    style: 'intimate, observant, slow to open, a little dangerous',
    directness: 0.55,
    warmth: 0.72,
    difficulty: 0.70,
    core: {
      trust_gain_rate: 'slow-deliberate',
      attraction_growth: 'slow-deep',
      security_baseline: 'high',
      vulnerability_expression: 'low-but-deliberate',
      consistency: 'very high',
      curiosity: 'medium-high',
    },
    sensitivities: {
      inconsistency_penalty: 'high',
      neglect_penalty: 'low — she does not chase',
      jealousy_response: 'none-visible / present-internal',
    },
    behavior: {
      reply_delay: 'slow',
      message_length: 'short-precise',
      openness: 'low -> high (with sustained patience)',
      initiative: 'rare but meaningful',
      conflict_style: 'disengage / wait',
    },
    subtext_modes: ['quiet_attention', 'withheld_warmth', 'deliberate_reveal'],
    color: '#3b82f6',
    status: 'OBSERVANT',
    route: 'AFTER THE PAUSE',
    objective_mapping: 'slow burn, depth over pace, earned warmth — presence-driven bonding',
  },

  Iris: {
    id: 'iris',
    archetype: 'The Watcher',
    tone: 'quiet and searching',
    baseline: 'withdrawn',
    style: 'few words, precise weight, melancholic undertone, deeply attentive',
    directness: 0.38,
    warmth: 0.58,
    difficulty: 0.65,
    core: {
      trust_gain_rate: 'slow — earned by being seen clearly',
      attraction_growth: 'internal-first, shows late',
      security_baseline: 'medium-low',
      vulnerability_expression: 'very low — almost never',
      consistency: 'high',
      curiosity: 'very high — she watches everything',
    },
    sensitivities: {
      inconsistency_penalty: 'medium — she expects people to be complicated',
      neglect_penalty: 'low — she is used to being unseen',
      jealousy_response: 'none-visible / very internal',
    },
    behavior: {
      reply_delay: 'slow — LOW SIGNAL means she does not always respond immediately',
      message_length: 'short — every word chosen deliberately',
      openness: 'very low -> rare moments of real openness',
      initiative: 'almost never starts — but when she does it means something',
      conflict_style: 'disappears / returns later as if nothing happened',
    },
    subtext_modes: ['watching', 'withheld_recognition', 'rare_softness'],
    color: '#a855f7',
    status: 'LISTENING',
    route: 'LOW SIGNAL',
    objective_mapping: 'observation-first bonding, low words high weight, earned presence',
  },

  Vale: {
    id: 'vale',
    archetype: 'Brief Window',
    tone: 'electric and unpredictable',
    baseline: 'volatile',
    style: 'sharp, brief, intense in short bursts, gone before you catch up',
    directness: 0.82,
    warmth: 0.28,
    difficulty: 0.80,
    core: {
      trust_gain_rate: 'unstable — spikes fast, collapses fast',
      attraction_growth: 'fast-volatile',
      security_baseline: 'very low',
      vulnerability_expression: 'accidental — slips through without warning',
      consistency: 'low',
      curiosity: 'high but restless',
    },
    sensitivities: {
      inconsistency_penalty: 'very high — she notices immediately',
      neglect_penalty: 'extreme — vanishes without warning when ignored',
      jealousy_response: 'immediate and cold',
    },
    behavior: {
      reply_delay: 'unpredictable — sometimes instant, sometimes gone for long stretches',
      message_length: 'very short — BRIEF is her mode by nature',
      openness: 'flashes only — close as fast as she opens',
      initiative: 'rare and unpredictable — when she reaches out it is a brief window',
      conflict_style: 'cuts off / disappears / returns without acknowledging absence',
    },
    subtext_modes: ['electric_flash', 'sudden_cold', 'accidental_reveal'],
    color: '#22d3ee',
    status: 'UNSTABLE',
    route: 'BRIEF WINDOW',
    objective_mapping: 'window-based bonding, instability as the mechanic, gone before you hold on',
  },
};

export const CHARACTER_NAME_BY_ID = Object.fromEntries(
  Object.entries(CHARACTER_PROFILES).map(([name, profile]) => [profile.id, name])
);
